name: checkout

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout traffic
        uses: actions/checkout@v2

      - name: Checkout
        env: 
          SOCKBOOM_LOGIN_URL: ${{secrets.SOCKBOOM_LOGIN_URL}}
          SOCKBOOM_CHECKIN_URL: ${{secrets.SOCKBOOM_CHECKIN_URL}}
          SOCKBOOM_USER: ${{secrets.SOCKBOOM_USER}}
          SOCKBOOM_PASSWD: ${{secrets.SOCKBOOM_PASSWD}}
        run: |
          import requests
          import sys
          import traceback

          form_data = {
            "email": "${{secrets.SOCKBOOM_USER}}",
            "passwd": "${{secrets.SOCKBOOM_PASSWD}}"
          }

          def run(form_data):
              s = requests.Session()
              response = s.post("${{secrets.SOCKBOOM_LOGIN_URL}}", data=form_data)
              print(response.text)
              print(response.status_code)
              if response.status_code == 200:
                  resp = s.post("${{secrets.SOCKBOOM_CHECKIN_URL}}")
                  print(resp.text)

          def main():
              run(form_data)
              print("run1")

          if __name__ == '__main__':
              try:
                  sys.exit(main())
              except Exception as e:
                  traceback.print_exc()
        shell: python

